### ISSUE TITLE
3D-ResNet-18 result

### ISSUE THREAD

**Issue by Fazlik995** [vt-vl-lab/SDN#3]
@jinwchoi 

Result in the paper for 3D-ResNet-18 algorithm (Table 1) is 83.5% on UCF101 and 53.6% on HMDB51.

Did you obtain these results pretraining model on Mini-Kinetics and fine-tuning on UCF101 and HMDB51 datasets?

If so, the difference of your result and [20] paper's result is so close to each other. How it can be explained since Mini-Kinetics dataset is 2 times smaller than Kinetics s dataset.

Please, clerify this situtation

Thank you!

**Comment by jinwchoi** [comment]
Hi @Fazlik995 

Yes. the results of 3D-ResNet-18 reported in the paper are from pre-training the model on Mini-Kinetics and then finetuning on UCF101/HMDB51/Diving48.  

I would say my results of 3D-ResNet-18 on UCF101 and HMDB51 are still lower than the results shown in [20] which is based on the full Kinetics. The size of the dataset and the performance does not follow linear relationship in general.
