### ISSUE TITLE
Difficulties installing Python requirements

### ISSUE THREAD

**Issue by AlexanderMelde** [vt-vl-lab/SDN#5]
Hello, 
i am trying to install the python requirements mentioned in your readme, but when executing the pip  command, i get the following error:

```
$ pip install -r sdn_packages.txt
ERROR: Invalid requirement: '_libgcc_mutex             0.1                        main' (from line 2 of sdn_packages.txt)
```
From my experience, `requirements.txt` files which are usually used with pip contain just the package names and optionally their versions, no build or channel information.

I found out that channels are used with anaconda, so i tried using a conda environment instead of the virtualenv i created before, but with pip, i get the same error, and the conda equivalent does not seem to be able to parse the line either:

```
$  conda install --file sdn_packages.txt
CondaValueError: could not parse '_libgcc_mutex             0.1                        main' in: sdn_packages.txt
```
As i am not very experiences with anaconda, i also tried creating a new environment using the command `conda create --name SDNauto --file sdn_packages.txt`, but this lead to the same error as `conda install`.

Could you please provide a working command for installing the requirements?

I am using Python 3.6 and Ubuntu 18.04.

Kind Regards
Alexander

**Comment by chamin96** [comment]
Hello @AlexanderMelde!

I get the same error. Did you find any solution for that?
Thank you.

**Comment by AlexanderMelde** [comment]
@chamin96
Unfortunately no, in my case it was easier to use an alternative action recognition framework.

**Comment by chamin96** [comment]
@AlexanderMelde Thanks for the reply.
I also tried to solve this by different methods, none of them worked. :-\

If anyone has a solution please help.

**Comment by jinwchoi** [comment]
You can install the required software and libraries individually. I am showing the important ones here. Hope this helps.

python 3.6
PyTorch 0.4.1 with CUDA 9: conda install pytorch=0.4.1 cuda90 -c pytorch
torchvision 0.2.1
ninja: conda install -c anaconda ninja
ffmpeg
numpy
pillow
opencv 3.4.2
pandas
yaml
scikit-learn
scikit-video
scipy
six
pyyaml
cython
