### ISSUE TITLE
how to understand the permutation?

### ISSUE THREAD

**Issue by gtv-Adam** [vt-vl-lab/SDN#6]
Hi Jinwoo Choi,

I am new to your project.
I noticed that in the dataset, in __getitem__, it will return 
clip = torch.stack(clip, 0).permute(1, 0, 2, 3) and the target.
Is it mean the clip's shape is [3, 12, 224, 224] , means the channel, number of frames and height and width of the input respectively?
What's the purpose of permute ?

Thanks

**Comment by jinwchoi** [comment]
Permutation is just changing the order of the dimensions.
